apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tripapi
spec:
  selector:
    matchLabels:
      app: tripapi
  template:
    metadata:
      labels:
        app: tripapi
    spec:
      containers:
      - image: registryugf9246.azurecr.io/tripinsights/tripapi:1.0
        name: tripapi
        env:
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: SQL_USER
          value: sqladminuGf9246
        - name: SQL_PASSWORD
          value: 8F4030Vk3
        - name: SQL_SERVER
          ="changeme.database.windows.net" \
    OPENAPI_UI_URI="http://changeme" \
    DEBUG_LOGGING="false"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None