kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: backend-policy
  namespace: api
spec:
  podSelector:
    matchLabels:
      app: tripapi
  ingress:
  - from:
    - namespaceSelector:
        matchlabels:
          name: web