apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        imagePullPolicy: Always
        image: "registryugf9246.azurecr.io/tripinsights/tripviewer:1.0"
        env:
          - name: USER_API_ENDPOINT
            value: "user.default.svc.cluster.local"
          - name: TRIPS_API_ENDPOINT
            value: "tripapi.default.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  labels:
    app: tripviewer
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: tripviewer
