apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tripapi
  namespace: api
spec:
  selector:
    matchLabels:
      app: tripapi
  template:
    metadata:
      labels:
        app: tripapi
    spec:
      containers:
      - image: registryugf9246.azurecr.io/tripinsights/tripapi:1.0
        name: tripapi
        imagePullPolicy: Always
        env:
          # Use secret in real usage
        - name: SQL_USER
          value: sqladminuGf9246
        - name: SQL_PASSWORD
          value: 8F4030Vk3
        - name: SQL_SERVER
          value: sqlserverugf9246.database.windows.net
        ports:
        - containerPort: 80
          name: tripapi
---
apiVersion: v1
kind: Service
metadata:
  name: tripapi
  namespace: api
spec:
  ports:
  - port: 80
  selector:
    app: tripapi