apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-java-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-java
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: user-java
        image: registryuGf9246.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 80
        env:
          - name: SQL_SERVER
            value: "sqlserverugf9246.database.windows.net"
          - name: SQL_DBNAME
            value: "mydrivingDB"
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: username
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: user-java-service
spec:
  selector:
    app: user-java
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
