apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: user-java-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: user-java
    spec:
      terminationGracePeriodSeconds: 20
      containers:
      - name: user-java
        image: registryuGf9246.azurecr.io/tripinsights/user-java:1.0
        ports:
        - containerPort: 8080